DROP TABLE if EXISTS users, items, comments, bookings;

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL UNIQUE,
  CONSTRAINT pk_user PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS items (
  item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512) NOT NULL,
  available boolean,
  owner BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
  count_rented INTEGER,
  CONSTRAINT pk_item PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS bookings(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT REFERENCES items(item_id) ON DELETE CASCADE,
    booked_user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL,
    status VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  item_id BIGINT REFERENCES items(item_id),
  author_id BIGINT REFERENCES users(user_id),
  text VARCHAR(50),
  created timestamp
);